name: ahk2exe

on: [push]

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Ahk2Exe
      uses: tamo/action-Ahk2Exe@multifile
      with:
        base: AutoHotkey32.exe,AutoHotkey64.exe
        src: RestoreWinPos.ahk

    - run: |
        mv RestoreWinPos32.exe RestoreWinPos.exe
        ls RestoreWinPos64.exe

    - name: Save artifacts
      uses: actions/upload-artifact@v4
      with:
        path: |
          RestoreWinPos.exe
          RestoreWinPos64.exe

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          RestoreWinPos.exe
          RestoreWinPos64.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
